
# https://www.bg-wiki.com/ffxi/Category:Automaton_Equipment
attachments = [
    {"Name":"Accelerator", "Element":"Wind", "Capacity":2, "Evasion":[5, 10, 15, 20]},
    {"Name":"Accelerator II", "Element":"Wind", "Capacity":3, "Evasion":[10, 15, 20, 25]},
    {"Name":"Accelerator III", "Element":"Wind", "Capacity":4, "Evasion":[20, 35, 40, 50]},
    {"Name":"Accelerator IV", "Element":"Wind", "Capacity":5, "Evasion":[30, 45, 60, 80]},
    {"Name":"Amplifier", "Element":"Ice", "Capacity":2, "Magic Burst Damage II":[10, 20, 35, 50]},
    {"Name":"Amplifier II", "Element":"Ice", "Capacity":3, "Magic Burst Damage II":[20, 30, 50, 70]},
    {"Name":"Analyzer", "Element":"Earth", "Capacity":1},
    {"Name":"Arcanic Cell", "Element":"Light", "Capacity":1, "Occult Acumen":[10, 20, 35, 50]},
    {"Name":"Arcanic Cell II", "Element":"Light", "Capacity":2, "Occult Acumen":[20, 40, 70, 100]},
    {"Name":"Arcanoclutch", "Element":"Ice", "Capacity":1, "Magic Attack":[20, 40, 60, 80]},
    {"Name":"Arcanoclutch II", "Element":"Ice", "Capacity":2, "Magic Attack":[40, 60, 80, 120]},
    {"Name":"Armor Plate", "Element":"Earth", "Capacity":2, "PDT":[-5, -7, -10, -15]},
    {"Name":"Armor Plate II", "Element":"Earth", "Capacity":3, "PDT":[-10, -15, -20, -25]},
    {"Name":"Armor Plate III", "Element":"Earth", "Capacity":4, "PDT":[-15, -20, -25, -30]},
    {"Name":"Armor Plate IV", "Element":"Earth", "Capacity":5, "PDT":[-20, -25, -30, -40]},
    {"Name":"Attuner", "Element":"Fire", "Capacity":2, "Ignore Defense%":[5, 15, 30, 45]},
    {"Name":"Auto-Repair Kit", "Element":"Light", "Capacity":2,},
    {"Name":"Auto-Rep. Kit II", "Element":"Light", "Capacity":3,},
    {"Name":"Auto-Rep. Kit III", "Element":"Light", "Capacity":4,},
    {"Name":"Auto-Rep. Kit IV", "Element":"Light", "Capacity":5,},
    {"Name":"Barrage Turbine", "Element":"Wind", "Capacity":2, "Barrage":[2,3,4,5]},
    {"Name":"Barrier Module", "Element":"Earth", "Capacity":1},
    {"Name":"Coiler", "Element":"Thunder", "Capacity":2, "DA":[3, 10, 20, 30]},
    {"Name":"Coiler II", "Element":"Thunder", "Capacity":3, "DA":[10, 15, 25, 35]},
    {"Name":"Condenser", "Element":"Water", "Capacity":1},
    {"Name":"Damage Gauge", "Element":"Light", "Capacity":1},
    {"Name":"Disruptor", "Element":"Dark", "Capacity":2},
    {"Name":"Drum Magazine", "Element":"Wind", "Capacity":2, "Ranged Attack Frequency":[-3, -6, -9, -15]},
    {"Name":"Dynamo", "Element":"Thunder", "Capacity":2, "Crit Rate":[3, 5, 7, 9]},
    {"Name":"Dynamo II", "Element":"Thunder", "Capacity":3, "Crit Rate":[5, 10, 15, 20]},
    {"Name":"Dynamo III", "Element":"Thunder", "Capacity":4, "Crit Rate":[10, 15, 25, 35]},
    {"Name":"Economizer", "Element":"Dark", "Capacity":1},
    {"Name":"Equalizer", "Element":"Earth", "Capacity":2},
    {"Name":"Eraser", "Element":"Light", "Capacity":2},
    {"Name":"Flame Holder", "Element":"Fire", "Capacity":1, "Weapon Skill Damage":[25, 100, 175, 250]},
    {"Name":"Flashbulb", "Element":"Light", "Capacity":2},
    {"Name":"Galvanizer", "Element":"Thunder", "Capacity":2, "Counter":[10, 20, 35, 50]},
    {"Name":"Hammermill", "Element":"Fire", "Capacity":1},
    {"Name":"Heat Capacitor", "Element":"Fire", "Capacity":1},
    {"Name":"Heat Capacitor II", "Element":"Fire", "Capacity":1},
    {"Name":"Heat Seeker", "Element":"Fire", "Capacity":1},
    {"Name":"Heatsink", "Element":"Fire", "Capacity":1},
    {"Name":"Ice Maker", "Element":"Fire", "Capacity":1},
    {"Name":"Inhibitor", "Element":"Fire", "Capacity":1},
    {"Name":"Inhibitor II", "Element":"Fire", "Capacity":1},
    {"Name":"Loudspeaker", "Element":"Fire", "Capacity":1},
    {"Name":"Loudspeaker II", "Element":"Fire", "Capacity":1},
    {"Name":"Loudspeaker III", "Element":"Fire", "Capacity":1},
    {"Name":"Loudspeaker IV", "Element":"Fire", "Capacity":1},
    {"Name":"Loudspeaker V", "Element":"Fire", "Capacity":1},
    {"Name":"Magniplug", "Element":"Fire", "Capacity":1},
    {"Name":"Magniplug II", "Element":"Fire", "Capacity":1},
    {"Name":"Mana Booster", "Element":"Fire", "Capacity":1},
    {"Name":"Mana Channeler", "Element":"Fire", "Capacity":1},
    {"Name":"Mana Conserver", "Element":"Fire", "Capacity":1},
    {"Name":"Mana Converter", "Element":"Fire", "Capacity":1},
    {"Name":"Mana Jammer", "Element":"Fire", "Capacity":1},
    {"Name":"Mana Jammer II", "Element":"Fire", "Capacity":1},
    {"Name":"Mana Jammer III", "Element":"Fire", "Capacity":1},
    {"Name":"Mana Jammer IV", "Element":"Fire", "Capacity":1},
    {"Name":"Mana Tank", "Element":"Fire", "Capacity":1},
    {"Name":"Mana Tank II", "Element":"Fire", "Capacity":1},
    {"Name":"Mana Tank III", "Element":"Fire", "Capacity":1},
    {"Name":"Mana Tank IV", "Element":"Fire", "Capacity":1},
    {"Name":"Optic Fiber", "Element":"Fire", "Capacity":1},
    {"Name":"Pattern Reader", "Element":"Fire", "Capacity":1},
    {"Name":"Percolator", "Element":"Fire", "Capacity":1},
    {"Name":"Power Cooler", "Element":"Fire", "Capacity":1},
    {"Name":"Reactive Shield", "Element":"Fire", "Capacity":1},
    {"Name":"Regulator", "Element":"Fire", "Capacity":1},
    {"Name":"Repeater", "Element":"Fire", "Capacity":1},
    {"Name":"Replicator", "Element":"Fire", "Capacity":1},
    {"Name":"Resister", "Element":"Fire", "Capacity":1},
    {"Name":"Resister II", "Element":"Fire", "Capacity":1},
    {"Name":"Scanner", "Element":"Fire", "Capacity":1},
    {"Name":"Schurzen", "Element":"Fire", "Capacity":1},
    {"Name":"Scope", "Element":"Fire", "Capacity":1},
    {"Name":"Scope II", "Element":"Fire", "Capacity":1},
    {"Name":"Scope III", "Element":"Fire", "Capacity":1},
    {"Name":"Scope IV", "Element":"Fire", "Capacity":1},
    {"Name":"Shock Absorber", "Element":"Fire", "Capacity":1},
    {"Name":"Shock Absorber II", "Element":"Fire", "Capacity":1},
    {"Name":"Shock Absorber III", "Element":"Fire", "Capacity":1},
    {"Name":"Smoke Screen", "Element":"Fire", "Capacity":1},
    {"Name":"Speedloader", "Element":"Fire", "Capacity":1},
    {"Name":"Speedloader II", "Element":"Fire", "Capacity":1},
    {"Name":"Stabilizer", "Element":"Fire", "Capacity":1},
    {"Name":"Stabilizer II", "Element":"Fire", "Capacity":1},
    {"Name":"Stabilizer III", "Element":"Fire", "Capacity":1},
    {"Name":"Stabilizer IV", "Element":"Fire", "Capacity":1},
    {"Name":"Stabilizer V", "Element":"Fire", "Capacity":1},
    {"Name":"Stealth Screen", "Element":"Fire", "Capacity":1},
    {"Name":"Stealth Screen II", "Element":"Fire", "Capacity":1},
    {"Name":"Steam Jacket", "Element":"Fire", "Capacity":1},
    {"Name":"Strobe", "Element":"Fire", "Capacity":1},
    {"Name":"Strobe II", "Element":"Fire", "Capacity":1},
    {"Name":"Tact. Processor", "Element":"Fire", "Capacity":1},
    {"Name":"Target Marker", "Element":"Fire", "Capacity":1},
    {"Name":"Ten. Spring II", "Element":"Fire", "Capacity":1},
    {"Name":"Ten. Spring III", "Element":"Fire", "Capacity":1},
    {"Name":"Ten. Spring IV", "Element":"Fire", "Capacity":1},
    {"Name":"Ten. Spring V", "Element":"Fire", "Capacity":1},
    {"Name":"Tension Spring", "Element":"Fire", "Capacity":1},
    {"Name":"Tranquilizer", "Element":"Fire", "Capacity":1},
    {"Name":"Tranquilizer II", "Element":"Fire", "Capacity":1},
    {"Name":"Tranquilizer III", "Element":"Fire", "Capacity":1},
    {"Name":"Tranquilizer IV", "Element":"Fire", "Capacity":1},
    {"Name":"Truesights", "Element":"Fire", "Capacity":1},
    {"Name":"Turbo Charger", "Element":"Fire", "Capacity":1},
    {"Name":"Turbo Charger II", "Element":"Fire", "Capacity":1},
    {"Name":"Vivi-Valve", "Element":"Fire", "Capacity":1},
    {"Name":"Vivi-valve II", "Element":"Fire", "Capacity":1},
    {"Name":"Volt Gun", "Element":"Fire", "Capacity":1},
]